version: "3.8"
services:
  web:
    build: .
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command: >
      bash -c "
      poetry run alembic upgrade head  &&
      poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "