version: "3.8"
services:
  db:
    image: postgres:13.21-alpine3.21
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: testdb
    ports:
      - "8000:8000"
    command: >
      bash -c "
      poetry run alembic upgrade head  &&
      poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
volumes:
  postgres_data:
